// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7bFaAYeeJJO__nNBiv39xyZ6EoIvpU1w',
    appId: '1:58899470341:web:a689a5672194576584a46c',
    messagingSenderId: '58899470341',
    projectId: 'monpressing-app-2026',
    authDomain: 'monpressing-app-2026.firebaseapp.com',
    storageBucket: 'monpressing-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT_4OgT6DKMQOEpVDERnhtSgCJTqUcVSk',
    appId: '1:58899470341:android:b27cc642b51d14d184a46c',
    messagingSenderId: '58899470341',
    projectId: 'monpressing-app-2026',
    storageBucket: 'monpressing-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6rX4rx5SKu5DnPtfKYlX57-R0hq1w1VY',
    appId: '1:58899470341:ios:321437eebad1cbd184a46c',
    messagingSenderId: '58899470341',
    projectId: 'monpressing-app-2026',
    storageBucket: 'monpressing-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.monpressing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6rX4rx5SKu5DnPtfKYlX57-R0hq1w1VY',
    appId: '1:58899470341:ios:321437eebad1cbd184a46c',
    messagingSenderId: '58899470341',
    projectId: 'monpressing-app-2026',
    storageBucket: 'monpressing-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.monpressing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7bFaAYeeJJO__nNBiv39xyZ6EoIvpU1w',
    appId: '1:58899470341:web:a7020926a17e7f3884a46c',
    messagingSenderId: '58899470341',
    projectId: 'monpressing-app-2026',
    authDomain: 'monpressing-app-2026.firebaseapp.com',
    storageBucket: 'monpressing-app-2026.firebasestorage.app',
  );
}
